### ISSUE TITLE
[BUG] Создание заклинаний возможно при полном отсутствии зарядов

### ISSUE THREAD

**Issue by TaggedDev** [North-Nomads/TundraGame#112]
**Описание бага/Bug description**
Количество зарядов в заклинании неограничено

**Воспроизведение/Steps to reproduce**
Шаги для воспроизведения бага:
1. Попробовать бесперерывно нажимать на элемент
2. Удалять элементы из руки при необходимости
3. Снова нажимать на элементы
4. Получим состояние, когда элемент визуально не имеет зарядов, но может быть добавлен в заклинание

**Ожидаемое поведение/Expected behaviour**
При 0% заряда, элемент не должен быть доступен для создания. **_При удалении элементов из руки, % заполненности должен быть увеличен_**

**Comment by IOExcept10n** [comment]
Проблема решена и отправлена в main
