### ISSUE TITLE
Break SpikesStunEffect [BUG]

### ISSUE THREAD

**Issue by mhl-popoff** [North-Nomads/TundraGame#115]
**Описание бага/Bug description**
Мобы станятся навсегда

**Воспроизведение/Steps to reproduce**
Шаги для воспроизведения бага:
Достаточно разовой активации

**Ожидаемое поведение/Expected behaviour**
Спустя время должен выходить из стана

**Comment by TaggedDev** [comment]
Проблема заключалась в том, что сначала эффект добавлялся в список эффектов, а потом проверялось, есть ли уже стан в списке (только что добавленный в нем был), после чего удалялся новоиспеченный эффект. Однако наложенный стан уже действовал.
