### ISSUE TITLE
[BUG] Мобы застревают на мосту

### ISSUE THREAD

**Issue by IOExcept10n** [North-Nomads/TundraGame#125]
**Описание бага/Bug description**
Перед мостом мобы могут застрять

**Воспроизведение/Steps to reproduce**
Шаги для воспроизведения бага:
1. Запустить игру

**Ожидаемое поведение/Expected behaviour**
Мобы должны спокойно проходить через мост

**Comment by TaggedDev** [comment]
Нужно опустить модель моста так, чтобы она не имела "порога". А ещё саму модель слегка удлиннить

**Comment by TaggedDev** [comment]
Проблема была в Transform[].GetComponentInChildren<Transform>(). Первое вхождение и был parent. К нему они и шли
