### ISSUE TITLE
[BUG] Молния остается в воздухе

### ISSUE THREAD

**Issue by TaggedDev** [North-Nomads/TundraGame#127]
**Описание бага/Bug description**
Прямая линия молнии остается бесконечно в воздухе 

**Воспроизведение/Steps to reproduce**
Шаги для воспроизведения бага:
1. С начала уровня запустить молнию в левый берег на первом уровне

**Ожидаемое поведение/Expected behaviour**
Молния бьет в землю и исчезает

**Скриншоты/Screenshoots** [not necessary/необязательно]
[(Скриншот)](https://media.discordapp.net/attachments/1050645887350743080/1100362174280511528/image.png?width=910&height=565)

**Comment by GalteXx** [comment]
fixed in [7d1c5da](https://github.com/North-Nomads/TundraGame/commit/7d1c5da72d3af2f7edfe187628a80424f11e7651)
