### ISSUE TITLE
[BUG] Кристал поднимает ошибку, если моб умер раньше

### ISSUE THREAD

**Issue by TaggedDev** [North-Nomads/TundraGame#129]
**Описание бага/Bug description**
Кристал выбрасывает ошибку, когда моб умирает до окончания заклинания

**Воспроизведение/Steps to reproduce**
Шаги для воспроизведения бага:
1. Заспавнить кристал
2. Сделать так, чтобы моб сагрился на него
3. Убить моба быстро, пока кристал ещё жив

**Ожидаемое поведение/Expected behaviour**
Ошибки быть не должно

**Скриншоты/Screenshoots** [not necessary/необязательно]
InvalidOperationException: Collection was modified; enumeration operation may not execute.
System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Spells.SpellClasses.LightningCrystalSpell.FixedUpdate () (at Assets/Scripts/Spells/SpellClasses/LightningCrystalSpell.cs:31)

**Дополнительный контекст/Context** [not necessary/необязательно]
Любая дополнительная информация, если есть. Если нет - удалите пункт

**Comment by GalteXx** [comment]
Fixed in [this pull request](https://github.com/North-Nomads/TundraGame/pull/134)
