### ISSUE TITLE
[ISSUE] Меню паузы слишком большое

### ISSUE THREAD

**Issue by IOExcept10n** [North-Nomads/TundraGame#33]
**Описание бага**
Кнопки на меню паузы слишком большие, осталась лишь одна кнопка Resume, которая закрывает весь экран

**Comment by TaggedDev** [comment]
Проблема ещё актуальная?

**Comment by IOExcept10n** [comment]
Не знаю насчёт последних билдов, но думаю, что до тех пор, пока не появится кнопка выхода из игры с меню паузы, она останется актуальной
