### ISSUE TITLE
[BUG] Иногда выход из уровня не работает

### ISSUE THREAD

**Issue by IOExcept10n** [North-Nomads/TundraGame#34]
**Описание бага**
После завершения всех волн иногда уровень не завершается, и в таком случае выйти из игры становится невозможным

**Воспроизведение**
Шаги для воспроизведения бага:
1. Убить всех мобов на уровне

**Comment by TaggedDev** [comment]
Я полагаю, что ошибка в том, что большое количество мобов ломает траекторию движения и какие-то мобы остаются внизу, под горкой

**Comment by IOExcept10n** [comment]
Да, ошибка была частично связана и с озером лавы, и с ironclad'ом. Идея в том, что если есть несколько сущностей, которые были созданы одновременно, то они могут сработать на одном мобе в один кадр, следовательно обработка урона могла привести к многократной обработке смерти моба. Для решения проблемы на данный момент подготовлены изменения в ветке afterbuild-level-fix

**Comment by TaggedDev** [comment]
Ошибка до сих пор присутствует в билде

**Comment by TaggedDev** [comment]
Ошибка пофикшена в mvp1.0.2.5
