### ISSUE TITLE
[ISSUE] Башня неточно встает на платформу

### ISSUE THREAD

**Issue by TaggedDev** [North-Nomads/TundraGame#36]
**Описание бага**
При строительстве башни, она не встает на платформу, а левитирует

**Воспроизведение**
1. Построить башню
2. Посмотреть между башней и платформой

**Ожидаемое поведение**
Платформа и башня должны совпадать

**Comment by TaggedDev** [comment]
А ещё нужно заменить модель платформы

**Comment by IOExcept10n** [comment]
Полагаю, что данный баг связан с логикой, по которой определяется высота башни. На данный момент точка установки рассчитывается с учётом масштаба башни. Так как высота башни меньше единицы, масштаб равный единице не будет ставить её ровно в нужную точку. Пока что ищу способы исправить это

**Comment by IOExcept10n** [comment]
Из вариантов – либо сделать саму модель башни ровно метр высотой, либо уменьшить её хитбокс и выставлять положение по нему
