### ISSUE TITLE
[BUG] Зомби игнорирует стену

### ISSUE THREAD

**Issue by DaSh-More** [North-Nomads/TundraGame#38]
**Описание бага**
Один из зомби проходит насквозь стены

**Воспроизведение**
Шаги для воспроизведения бага:
1. Запустить уровень
2. Дождаться прохода зомби, не убивая

**Ожидаемое поведение**
Зомби наносит урон стене и исчезает

**Скриншоты**
![Screenshot_2023-02-10-10-56-39-26_2b60f13f3137f87460b04103ffd368b4.jpg](https://user-images.githubusercontent.com/52647986/218051669-04b59e84-2de7-4b0b-af5f-71daaf561c34.jpg)

**Comment by IOExcept10n** [comment]
Данный баг связан с отсутствием коллайдера у боковых частей стены. Полагаю, что они должны работать так же, как и центральные ворота. @TaggedDev , предлагаю объединить все части стены в один GameObject и повесить на него скрипт Gates так, чтобы он срабатывал для любого коллайдера на них
