### ISSUE TITLE
[ISSUE] Проблемы с направлением движения мобов

### ISSUE THREAD

**Issue by IOExcept10n** [North-Nomads/TundraGame#40]
**Описание бага**
Мобы в игре могут смотреть не в ту сторону, куда нужно, а также неконтролируемо крутиться вокруг своей оси

**Воспроизведение**
Шаги для воспроизведения бага:
1. Запустить волну и пронаблюдать за поведением мобов

**Ожидаемое поведение**
Направленное движение к воротам без лишних отклонений

**Comment by TaggedDev** [comment]
Исправлено вместе с #39
