### ISSUE TITLE
[BUG] The right side of all fire tower modifications blocks spell casting

### ISSUE THREAD

**Issue by TaggedDev** [North-Nomads/TundraGame#83]
**Описание бага/Bug description**
При изучении всех правых талантов, заклинание огня перестает призываться

**Воспроизведение/Steps to reproduce**
1. Запустить игру
2. Прокачать правые таланты в башне огня
3. Создать заклинание огня

**Ожидаемое поведение/Expected behaviour**
Выполнения логики заклинания огня с заданными модификациями

**Comment by TaggedDev** [comment]
У меня такого бага не наблюдается, проверьте кто-нибудь ещё. Если есть подтверждение - навесьте ярлык [CONFIRMED]

**Comment by IOExcept10n** [comment]
Баг не нашёл, всё работает нормально
