### ISSUE TITLE
[BUG] Pause menu and levels menu is too high

### ISSUE THREAD

**Issue by TaggedDev** [North-Nomads/TundraGame#85]
**Описание бага/Bug description**
Меню паузы и меню уровней улетает слишком высоко

**Воспроизведение/Steps to reproduce**
1. Откройте сцену с уровнями
2. Обратите внимание на надпись LEVELS и на отсутствие кнопок с уровнями (а они там есть, где-то)\

1. Откройте игру
2. Поставьте игру на паузу
3. Обратите внимание на текст PAUSED

**Ожидаемое поведение/Expected behaviour**
Текст должен нормально отображаться. Количество уровней должно подтягиваться в квадратные кнопки и отображаться сеткой

**Comment by IOExcept10n** [comment]
I guess this bug has already been fixed
