### ISSUE TITLE
[BUG] Main menu buttons alignment

### ISSUE THREAD

**Issue by IOExcept10n** [North-Nomads/TundraGame#93]
**Описание бага/Bug description**
Проблема с расположением кнопок меню

**Воспроизведение/Steps to reproduce**
Шаги для воспроизведения бага:
1. Запустить игру

**Скриншоты/Screenshoots** [not necessary/необязательно]
![Screenshot_20230311_020712_com.NorthNomads.TundraTD.jpg](https://user-images.githubusercontent.com/56886020/224471973-b697618c-4f17-42f9-b883-a9a7083815e5.jpg)

**Comment by TaggedDev** [comment]
Fixed in #96 (Alpha2.1.0.0)
