### ISSUE TITLE
[ISSUE] Pause menu is a little bit bigger than screen size

### ISSUE THREAD

**Issue by TaggedDev** [North-Nomads/TundraGame#99]
**Описание бага/Bug description**
При открытии меню паузы оно вылезает за рамки

**Воспроизведение/Steps to reproduce**
Шаги для воспроизведения бага:
1. Зайти в уровень
2. Открыть паузу

**Ожидаемое поведение/Expected behaviour**
Канвас паузы должен полностью влезать в экран телефона

**Скриншоты/Screenshoots** [not necessary/необязательно]
[Скриншот](https://media.discordapp.net/attachments/996695195552850020/1085200134838689873/image.png?width=1394&height=643)

**Comment by GalteXx** [comment]
fixed in Commit [3e4b31d](https://github.com/North-Nomads/TundraGame/commit/3e4b31dd2c02623c99293fd7568a0ee1a2749031)
